# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e97211a15648695407e2cf86e78ee2c30badc2dd8301129ba90f4d41cfee7abb6df625dd39c4eba65fd8a1492546cca870bec9b049bc05c2ceebb197f3c5239f

test:
  secret_key_base: 1b4fbad2cb22be97de39b5aa77c72f28740d72a25a79ebd228a00c203d60a1cdf9d2dfcbaa31086f85bb89fd5d9307133a90898eec1eb54f2330ad3c723cd5b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
